### PR TITLE
Add sentry router tracing and new ErrorBoundary component

### PR DESCRIPTION
**Pull request by harshithmohan**
- Pending: Add image

### CODE REVIEW

**Comment by harshithmohan** [comment]
Current dependencies on/for this PR:
* master
  * **PR #670** <a href="https://app.graphite.dev/github/pr/ShokoAnime/Shoko-WebUI/670" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/ShokoAnime/Shoko-WebUI/670?utm_source=stack-comment).

**Review by hidden4003 — APPROVED** [review]

**Comment by ElementalCrisis** [comment]
@harshithmohan is this good to go?

**Comment by harshithmohan** [comment]
> @harshithmohan is this good to go?

@hidden4003 said something about changing the text to less technical. Are we doing it?

**Comment by hidden4003** [comment]
I only asked to rephrase the text ` If crashed during an update, select Force Update to Stable Web UI, otherwise select Logout of Web UI to clear local storage.` as it seems a bit too technical and complicated to read.

**Pull request merged**
